<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HP-LAPTOP-SACHIT" ignored="0" name="Test" tests="4" failures="3" timestamp="2023-08-18T13:35:55 IST" time="42.602" errors="0">
  <testcase name="Login" time="0.622" classname="com.qa.TestScripts.TC_GuruWeb_001">
    <failure type="java.lang.AssertionError" message="did not expect [User or Password is not valid] but found [User or Password is not valid]">
      <![CDATA[java.lang.AssertionError: did not expect [User or Password is not valid] but found [User or Password is not valid]
at com.qa.TestScripts.TC_GuruWeb_001.Login(TC_GuruWeb_001.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase name="Login" time="1.529" classname="com.qa.TestScripts.TC_GuruWeb_001"/>
  <testcase name="Login" time="0.61" classname="com.qa.TestScripts.TC_GuruWeb_001">
    <failure type="java.lang.AssertionError" message="did not expect [User or Password is not valid] but found [User or Password is not valid]">
      <![CDATA[java.lang.AssertionError: did not expect [User or Password is not valid] but found [User or Password is not valid]
at com.qa.TestScripts.TC_GuruWeb_001.Login(TC_GuruWeb_001.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase name="Login" time="0.686" classname="com.qa.TestScripts.TC_GuruWeb_001">
    <failure type="java.lang.AssertionError" message="did not expect [User or Password is not valid] but found [User or Password is not valid]">
      <![CDATA[java.lang.AssertionError: did not expect [User or Password is not valid] but found [User or Password is not valid]
at com.qa.TestScripts.TC_GuruWeb_001.Login(TC_GuruWeb_001.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
</testsuite> <!-- Test -->
